# -*- coding: utf-8 -*-
"""QRIS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1njAH0uDlNUarxyjAx9krgTlqIltry20V
"""

import pandas as pd # Mengimpor library pandas untuk manipulasi data

# Memuat file Excel ke dalam DataFrame pandas
df = pd.read_excel('/content/drive/MyDrive/Dataset/Dataset_Clean.xlsx')

# Menampilkan 5 baris pertama dari DataFrame
display(df.head())

import os # Mengimpor library os untuk berinteraksi dengan sistem operasi

# Menentukan jalur ke folder 'Dataset' di Google Drive
dataset_path = '/content/drive/MyDrive/Dataset/'

print(f"Listing contents of: {dataset_path}") # Menampilkan pesan listing folder
# Memeriksa apakah direktori ada
if os.path.exists(dataset_path):
    # Jika ada, iterasi dan cetak setiap item (file/folder) di dalamnya
    for item in os.listdir(dataset_path):
        print(item)
else:
    # Jika tidak ada, cetak pesan bahwa direktori tidak ditemukan
    print(f"The directory '{dataset_path}' does not exist or is not accessible.")

from google.colab import drive # Mengimpor modul drive dari google.colab
drive.mount('/content/drive') # Memasang (mount) Google Drive ke lingkungan Colab

import pandas as pd # Mengimpor library pandas

# Mengatur opsi pandas untuk menampilkan semua kolom
pd.set_option('display.max_columns', None)

# Menghapus kolom-kolom yang seluruhnya kosong (berisi semua nilai NaN)
df = df.dropna(axis=1, how='all')

# Menampilkan 5 baris pertama dari DataFrame setelah penghapusan kolom
display(df.head())

from sklearn.svm import SVC # Mengimpor Support Vector Classifier
from sklearn.metrics import accuracy_score, classification_report # Mengimpor metrik evaluasi model

# Menginisialisasi model Support Vector Classifier dengan kernel RBF
svm_model = SVC(kernel='rbf', random_state=42)

# Melatih model menggunakan data pelatihan yang sudah diskalakan
svm_model.fit(X_train_scaled, y_train)

# Membuat prediksi pada data pengujian yang sudah diskalakan
y_pred = svm_model.predict(X_test_scaled)

# Mengevaluasi kinerja model
print("Model training complete. Here are the evaluation metrics:")
print(f"Accuracy: {accuracy_score(y_test, y_pred):.2f}") # Menampilkan akurasi
print("\nClassification Report:\n", classification_report(y_test, y_pred)) # Menampilkan classification report

# 1. Mengimpor modul drive dari google.colab dan memasang (mount) Google Drive.
from google.colab import drive
drive.mount('/content/drive')

# 2. Mengimpor library pandas dan memuat file Excel ke dalam DataFrame.
import pandas as pd

# Memuat file Excel ke dalam DataFrame pandas
df = pd.read_excel('/content/drive/MyDrive/Dataset/Dataset_Clean.xlsx')

# Menampilkan 5 baris pertama dari DataFrame untuk melihat data awal
print("Data Awal (5 Baris Pertama):")
display(df.head())

# Mengatur opsi pandas untuk menampilkan semua kolom
pd.set_option('display.max_columns', None)

# Menghapus kolom-kolom yang seluruhnya kosong (berisi semua nilai NaN)
df = df.dropna(axis=1, how='all')

print("\nData setelah menghapus kolom yang seluruhnya kosong (5 Baris Pertama):")
display(df.head())

# 3. Mendefinisikan variabel target (y) dan fitur (X), serta menjatuhkan kolom yang tidak relevan.

# Mendefinisikan variabel target
y = df['Label']

# Mendefinisikan fitur dengan menjatuhkan kolom target dan kolom-kolom lain yang tidak digunakan.
# 'Unnamed: 27' dijatuhkan karena memiliki terlalu banyak NaN.
# 'Saya lebih sering bertransaksi di toko modern' dijatuhkan sesuai instruksi pengguna.
X = df.drop(columns=['Label', 'Unnamed: 27', 'Saya lebih sering bertransaksi di toko modern'])

print("Fitur (X) head setelah menjatuhkan kolom:")
display(X.head())
print("\nTarget (y) head:")
display(y.head())

# Memeriksa kembali NaN di X setelah drop kolom
print("\nJumlah NaN per kolom di X sebelum menghapus baris:")
display(X.isnull().sum()[X.isnull().sum() > 0])

# 4. Langkah Krusial: Menangani nilai NaN dengan menjatuhkan baris yang mengandung NaN.

# Menggabungkan X dan y untuk menjatuhkan baris dengan NaN secara konsisten di keduanya.
# Ini penting agar indeks X dan y tetap selaras setelah penghapusan baris.
df_combined_for_nan_drop = pd.concat([X, y], axis=1)

# Menjatuhkan baris yang mengandung nilai NaN apa pun di df_combined_for_nan_drop.
df_combined_cleaned = df_combined_for_nan_drop.dropna()

# Memisahkan X dan y lagi dari DataFrame gabungan yang sudah dibersihkan.
X = df_combined_cleaned.drop(columns=['Label'])
y = df_combined_cleaned['Label']

print(f"Shape of X setelah menghapus baris dengan NaNs: {X.shape}")
print(f"Shape of y setelah menghapus baris dengan NaNs: {y.shape}")
print("\nJumlah NaN per kolom di X setelah membersihkan baris (seharusnya 0 untuk semua):")
display(X.isnull().sum()[X.isnull().sum() > 0])
print("Jumlah NaN per kolom di y setelah membersihkan baris (seharusnya 0 untuk semua):")
display(y.isnull().sum()[y.isnull().sum() > 0])

# 5. Membagi data menjadi set pelatihan dan pengujian, serta menskalakan fitur.
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Membagi data menjadi set pelatihan (80%) dan pengujian (20%).
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("\nJumlah NaN di X_train sebelum penskalaan:")
display(X_train.isnull().sum()[X_train.isnull().sum() > 0])
print("Jumlah NaN di X_test sebelum penskalaan:")
display(X_test.isnull().sum()[X_test.isnull().sum() > 0])

# Menginisialisasi StandardScaler untuk penskalaan fitur.
scaler = StandardScaler()

# Melatih scaler pada data pelatihan dan mengubah (transform) data pelatihan serta pengujian.
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Menampilkan bentuk dataset hasil pembagian dan penskalaan.
print(f"\nShape X_train_scaled: {X_train_scaled.shape}")
print(f"Shape X_test_scaled: {X_test_scaled.shape}")
print(f"Shape y_train: {y_train.shape}")
print(f"Shape y_test: {y_test.shape}")

# Memeriksa NaN di data yang sudah diskalakan (seharusnya 0).
import numpy as np
print("\nJumlah NaN di X_train_scaled setelah penskalaan:", np.isnan(X_train_scaled).sum())
print("Jumlah NaN di X_test_scaled setelah penskalaan:", np.isnan(X_test_scaled).sum())

# 6. Melatih dan mengevaluasi model Support Vector Machine (SVM) sebelum hyperparameter tuning.
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

# Menginisialisasi model Support Vector Classifier dengan kernel RBF.
svm_model_before_tuning = SVC(kernel='rbf', random_state=42)

# Melatih model menggunakan data pelatihan yang sudah diskalakan.
print("Memulai pelatihan model SVM sebelum tuning...")
svm_model_before_tuning.fit(X_train_scaled, y_train)
print("Pelatihan model SVM sebelum tuning selesai.")

# Membuat prediksi pada data pengujian yang sudah diskalakan.
y_pred_before_tuning = svm_model_before_tuning.predict(X_test_scaled)

# Mengevaluasi kinerja model.
print("\nEvaluasi Model SVM (Sebelum Tuning):")
print(f"Accuracy: {accuracy_score(y_test, y_pred_before_tuning):.2f}")
print("\nClassification Report:\n", classification_report(y_test, y_pred_before_tuning))

# 7. Melakukan Hyperparameter Tuning menggunakan GridSearchCV untuk menemukan parameter terbaik.
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

# Mendefinisikan parameter grid untuk GridSearchCV.
param_grid = {
    'C': [0.1, 1, 10, 100], # Parameter regularisasi
    'gamma': [0.001, 0.01, 0.1, 1], # Koefisien kernel
    'kernel': ['rbf']
}

# Menginisialisasi Support Vector Classifier dasar.
svm_base_model = SVC(random_state=42)

# Menginisialisasi GridSearchCV (cv=5 untuk 5-fold cross-validation).
print("Memulai GridSearchCV untuk tuning hyperparameter...")
grid_search = GridSearchCV(svm_base_model, param_grid, cv=5, verbose=3, n_jobs=-1)

# Melatih GridSearchCV pada data pelatihan yang sudah diskalakan.
grid_search.fit(X_train_scaled, y_train)
print("GridSearchCV selesai.")

# Menampilkan parameter terbaik dan skor terbaik yang ditemukan.
print("\nParameter terbaik yang ditemukan:", grid_search.best_params_)
print("Akurasi cross-validation terbaik:", f"{grid_search.best_score_:.2f}")

# Mendapatkan estimator (model) terbaik dari GridSearchCV.
best_svm_model = grid_search.best_estimator_

# Membuat prediksi pada data pengujian menggunakan model terbaik.
y_pred_tuned = best_svm_model.predict(X_test_scaled)

# Mengevaluasi model terbaik pada set pengujian.
print("\nEvaluasi Model Terbaik pada Data Pengujian:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_tuned):.2f}")
print("\nClassification Report:\n", classification_report(y_test, y_pred_tuned))

# 8. Melatih dan mengevaluasi model SVM menggunakan parameter terbaik setelah tuning.
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

# Parameter terbaik yang ditemukan dari GridSearchCV.
best_params = {'C': 1, 'gamma': 0.01, 'kernel': 'rbf'}

# Menginisialisasi Support Vector Classifier dengan parameter terbaik.
svm_model_after_tuning = SVC(**best_params, random_state=42)

# Melatih model menggunakan data pelatihan yang sudah diskalakan.
print("Memulai pelatihan model SVM setelah tuning...")
svm_model_after_tuning.fit(X_train_scaled, y_train)
print("Pelatihan model SVM setelah tuning selesai.")

# Membuat prediksi pada data pengujian yang sudah diskalakan.
y_pred_after_tuning = svm_model_after_tuning.predict(X_test_scaled)

# Mengevaluasi kinerja model.
print("\nEvaluasi Model SVM (Setelah Tuning):")
print(f"Accuracy: {accuracy_score(y_test, y_pred_after_tuning):.2f}")
print("\nClassification Report:\n", classification_report(y_test, y_pred_after_tuning))

# 9. Menginisialisasi studi ablasi fitur.
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Menghitung akurasi baseline menggunakan y_test dan y_pred_after_tuning dari model terbaik.
baseline_accuracy = accuracy_score(y_test, y_pred_after_tuning)
print(f"Baseline Accuracy (Semua Fitur): {baseline_accuracy:.4f}")

# Menginisialisasi dictionary kosong untuk menyimpan hasil ablasi.
ablation_results = {}

# Menambahkan akurasi baseline ke ablation_results.
ablation_results['All Features'] = baseline_accuracy

# Mendefinisikan parameter terbaik yang ditemukan dari GridSearchCV.
best_params = {'C': 1, 'gamma': 0.01, 'kernel': 'rbf'}

# Mendapatkan nama fitur dari DataFrame X.
feature_names = X.columns.tolist()

print("\nMemulai Studi Ablasi Fitur...")

# 10. Melakukan iterasi studi ablasi fitur (menghapus satu fitur, melatih ulang, dan mengevaluasi).
print("Melakukan Ablasi Fitur...")

for feature_to_remove in feature_names:
    print(f"Memproses: Menghapus fitur '{feature_to_remove}'")

    # 1. Membuat set fitur sementara dengan menjatuhkan satu fitur.
    X_ablated = X.drop(columns=[feature_to_remove])

    # 2. Membagi ulang data menjadi set pelatihan dan pengujian.
    X_train_ablated, X_test_ablated, y_train_ablated, y_test_ablated = train_test_split(
        X_ablated, y, test_size=0.2, random_state=42
    )

    # 3. Menskalakan ulang set fitur pelatihan dan pengujian yang baru.
    scaler = StandardScaler()
    X_train_ablated_scaled = scaler.fit_transform(X_train_ablated)
    X_test_ablated_scaled = scaler.transform(X_test_ablated)

    # 4. Melatih model SVM terbaik pada data pelatihan yang sudah diablasikan dan diskalakan.
    svm_ablated_model = SVC(**best_params, random_state=42)
    svm_ablated_model.fit(X_train_ablated_scaled, y_train_ablated)

    # 5. Membuat prediksi pada data pengujian yang sudah diablasikan dan diskalakan.
    y_pred_ablated = svm_ablated_model.predict(X_test_ablated_scaled)

    # 6. Mengevaluasi akurasi model dan menyimpan hasilnya.
    ablated_accuracy = accuracy_score(y_test_ablated, y_pred_ablated)
    ablation_results[feature_to_remove] = ablated_accuracy
    print(f"  Akurasi tanpa '{feature_to_remove}': {ablated_accuracy:.4f}")

print("\nStudi Ablasi Fitur Selesai.")

# 12. Meringkas temuan dari studi ablasi fitur.
print("\n--- Ringkasan Studi Ablasi Fitur ---")
print(f"Baseline Accuracy (dengan semua fitur): {baseline_accuracy:.4f}")

most_impactful_positive = ablation_df_sorted[ablation_df_sorted['Accuracy Change'] > 0].sort_values(by='Accuracy Change', ascending=False)
most_impactful_negative = ablation_df_sorted[ablation_df_sorted['Accuracy Change'] < 0].sort_values(by='Accuracy Change', ascending=True)

if not most_impactful_positive.empty:
    print("\nFitur yang penghapusannya *meningkatkan* akurasi (menunjukkan noise atau redundansi):")
    for _, row in most_impactful_positive.iterrows():
        print(f"- '{row['Feature Removed']}': Akurasi meningkat sebesar {row['Accuracy Change']:.4f}")
else:
    print("\nTidak ada fitur yang meningkatkan akurasi saat dihapus.")

if not most_impactful_negative.empty:
    print("\nFitur yang penghapusannya *menurunkan* akurasi (menunjukkan kepentingan tinggi):")
    for _, row in most_impactful_negative.iterrows():
        print(f"- '{row['Feature Removed']}': Akurasi menurun sebesar {abs(row['Accuracy Change']):.4f}")
else:
    print("\nTidak ada fitur yang menurunkan akurasi secara signifikan saat dihapus.")

print("\nObservasi:")
print("- 'Accuracy Change' negatif yang lebih besar menunjukkan fitur yang lebih penting untuk kinerja model.")
print("- 'Accuracy Change' positif menunjukkan bahwa penghapusan fitur justru meningkatkan kinerja, menunjukkan mungkin ada noise atau redundansi.")

# 13. Menghitung dan memvisualisasikan Confusion Matrix untuk model terbaik.
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

# Menghitung confusion matrix untuk model yang sudah disetel.
cm = confusion_matrix(y_test, y_pred_after_tuning)

# Memplot confusion matrix.
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Greens',
            xticklabels=['Diprediksi 0', 'Diprediksi 1'],
            yticklabels=['Aktual 0', 'Aktual 1'])
plt.xlabel('Label Diprediksi')
plt.ylabel('Label Sebenarnya')
plt.title('Confusion Matrix untuk Model SVM yang Disetel')
plt.show()

# 14. Memeriksa distribusi variabel target (y).

print("Distribusi variabel target (y):")
display(y.value_counts())

print("\nDistribusi persentase variabel target (y):")
display(y.value_counts(normalize=True) * 100)

# Memeriksa nilai NaN di X_train sebelum penskalaan
print("NaN values in X_train before scaling:\n", X_train.isnull().sum()[X_train.isnull().sum() > 0])

# Memeriksa nilai NaN di X_train_scaled setelah penskalaan
import numpy as np # Mengimpor library numpy
print("\nNaN values in X_train_scaled after scaling:\n", np.isnan(X_train_scaled).sum(axis=0)) # Menghitung NaN per kolom

# Memeriksa apakah ada kolom di X_train_scaled yang seluruhnya NaN
print("\nColumns in X_train_scaled with all NaNs:", np.all(np.isnan(X_train_scaled), axis=0).sum())

# Mengidentifikasi kolom di X_train yang menyebabkan NaN setelah penskalaan
nan_columns_in_scaled = X_train.columns[np.where(np.isnan(X_train_scaled).sum(axis=0) > 0)[0]]
print("\nColumns in original X_train that result in NaNs after scaling:", nan_columns_in_scaled.tolist())

# Memuat ulang data awal dan definisi fitur/target hingga df_combined
import pandas as pd # Mengimpor library pandas

df = pd.read_excel('/content/drive/MyDrive/Dataset/Dataset_Clean.xlsx') # Memuat file Excel
pd.set_option('display.max_columns', None) # Mengatur opsi tampilkan semua kolom
df = df.dropna(axis=1, how='all') # Menghapus kolom yang seluruhnya kosong

y = df['Label'] # Mendefinisikan variabel target
X = df.drop(columns=['Label', 'Saya lebih sering bertransaksi di toko modern']) # Mendefinisikan fitur dengan menjatuhkan kolom tertentu

df_combined = pd.concat([X, y], axis=1) # Menggabungkan X dan y menjadi satu DataFrame

print("Shape of df_combined BEFORE dropping NaNs:", df_combined.shape) # Menampilkan bentuk DataFrame sebelum menghapus NaN
print("\nNumber of NaN values per column in df_combined BEFORE dropping NaNs:") # Menampilkan jumlah NaN per kolom sebelum menghapus NaN
display(df_combined.isnull().sum()[df_combined.isnull().sum() > 0]) # Menampilkan kolom dengan NaN

# Melihat efek setelah menghapus NaN
df_combined_cleaned = df_combined.dropna() # Menghapus baris yang mengandung NaN

print("\nShape of df_combined AFTER dropping NaNs:", df_combined_cleaned.shape) # Menampilkan bentuk DataFrame setelah menghapus NaN
print("\nNumber of NaN values per column in df_combined AFTER dropping NaNs (should be 0 for all):") # Menampilkan jumlah NaN per kolom setelah menghapus NaN (seharusnya 0)
display(df_combined_cleaned.isnull().sum()[df_combined_cleaned.isnull().sum() > 0])

from sklearn.model_selection import train_test_split # Mengimpor fungsi untuk membagi data
from sklearn.preprocessing import StandardScaler # Mengimpor StandardScaler untuk penskalaan fitur

# Membagi data menjadi set pelatihan dan pengujian
# Menggunakan rasio 80% untuk pelatihan dan 20% untuk pengujian
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Menginisialisasi StandardScaler
scaler = StandardScaler()

# Melatih scaler pada data pelatihan dan mengubah data pelatihan serta pengujian
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Menampilkan bentuk dataset hasil pembagian dan penskalaan
print(f"Shape of X_train_scaled: {X_train_scaled.shape}")
print(f"Shape of X_test_scaled: {X_test_scaled.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

"""### Model Training (Before Hyperparameter Tuning)"""

from sklearn.svm import SVC # Mengimpor Support Vector Classifier
from sklearn.metrics import accuracy_score, classification_report # Mengimpor metrik evaluasi model

# Menginisialisasi model Support Vector Classifier dengan kernel RBF
svm_model_before_tuning = SVC(kernel='rbf', random_state=42)

# Melatih model menggunakan data pelatihan yang sudah diskalakan
svm_model_before_tuning.fit(X_train_scaled, y_train)

# Membuat prediksi pada data pengujian yang sudah diskalakan
y_pred_before_tuning = svm_model_before_tuning.predict(X_test_scaled)

# Mengevaluasi kinerja model
print("Model training complete (before tuning). Here are the evaluation metrics:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_before_tuning):.2f}") # Menampilkan akurasi
print("\nClassification Report:\n", classification_report(y_test, y_pred_before_tuning)) # Menampilkan classification report

from google.colab import drive # Mengimpor modul drive dari google.colab
drive.mount('/content/drive') # Memasang (mount) Google Drive ke lingkungan Colab

import pandas as pd # Mengimpor library pandas untuk manipulasi data

# Memuat file Excel ke dalam DataFrame pandas
df = pd.read_excel('/content/drive/MyDrive/Dataset/Dataset_Clean.xlsx')

# Menampilkan 5 baris pertama dari DataFrame
display(df.head())

import os # Mengimpor library os untuk berinteraksi dengan sistem operasi

# Menentukan jalur ke folder 'Dataset' di Google Drive
dataset_path = '/content/drive/MyDrive/Dataset/'

print(f"Listing contents of: {dataset_path}") # Menampilkan pesan listing folder
# Memeriksa apakah direktori ada
if os.path.exists(dataset_path):
    # Jika ada, iterasi dan cetak setiap item (file/folder) di dalamnya
    for item in os.listdir(dataset_path):
        print(item)
else:
    # Jika tidak ada, cetak pesan bahwa direktori tidak ditemukan
    print(f"The directory '{dataset_path}' does not exist or is not accessible.")

import pandas as pd # Mengimpor library pandas

# Mengatur opsi pandas untuk menampilkan semua kolom
pd.set_option('display.max_columns', None)

# Menghapus kolom-kolom yang seluruhnya kosong (berisi semua nilai NaN)
df = df.dropna(axis=1, how='all')

# Menampilkan 5 baris pertama dari DataFrame setelah penghapusan kolom
display(df.head())

# Mendefinisikan variabel target (y)
y = df['Label']

# Mendefinisikan fitur (X) dengan menjatuhkan kolom target dan kolom-kolom yang ditentukan dari DataFrame
# 'Tempat saya berbelanja lebih banyak menyediakan QRIS' dihapus dari daftar drop sesuai tindakan manual pengguna
X = df.drop(columns=['Label', 'Unnamed: 27', 'Saya lebih sering bertransaksi di toko modern']) # Kolom yang dijatuhkan

# Menampilkan beberapa baris pertama dari X dan y untuk konfirmasi
print("Features (X) head:")
display(X.head()) # Menampilkan head dari DataFrame fitur
print("\nTarget (y) head:")
display(y.head()) # Menampilkan head dari Series target

# --- Langkah Krusial: Tangani nilai NaN dengan menjatuhkan baris dari X dan y ---
# Menggabungkan X dan y untuk menjatuhkan baris dengan NaN secara konsisten di keduanya
df_combined = pd.concat([X, y], axis=1)

# Menjatuhkan baris yang mengandung nilai NaN apa pun
df_combined_cleaned = df_combined.dropna()

# Memisahkan X dan y lagi dari DataFrame gabungan yang sudah dibersihkan
X = df_combined_cleaned.drop(columns=['Label']) # Fitur X yang sudah bersih
y = df_combined_cleaned['Label'] # Variabel target y yang sudah bersih

print(f"Shape of X after dropping rows with NaNs: {X.shape}") # Menampilkan bentuk X setelah drop NaNs
print(f"Shape of y after dropping rows with NaNs: {y.shape}") # Menampilkan bentuk y setelah drop NaNs
print("Number of NaN values per column in X after cleaning:") # Menampilkan jumlah NaN per kolom di X (seharusnya 0)
display(X.isnull().sum()[X.isnull().sum() > 0])
print("Number of NaN values per column in y after cleaning:") # Menampilkan jumlah NaN per kolom di y (seharusnya 0)
display(y.isnull().sum()[y.isnull().sum() > 0])

from sklearn.model_selection import train_test_split # Mengimpor fungsi untuk membagi data
from sklearn.preprocessing import StandardScaler # Mengimpor StandardScaler untuk penskalaan fitur

# Membagi data menjadi set pelatihan dan pengujian
# Menggunakan rasio 80% untuk pelatihan dan 20% untuk pengujian
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Menginisialisasi StandardScaler
scaler = StandardScaler()

# Melatih scaler pada data pelatihan dan mengubah data pelatihan serta pengujian
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Menampilkan bentuk dataset hasil pembagian dan penskalaan
print(f"Shape of X_train_scaled: {X_train_scaled.shape}")
print(f"Shape of X_test_scaled: {X_test_scaled.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

from sklearn.svm import SVC # Mengimpor Support Vector Classifier
from sklearn.metrics import accuracy_score, classification_report # Mengimpor metrik evaluasi model

# Menginisialisasi model Support Vector Classifier dengan kernel RBF
svm_model_before_tuning = SVC(kernel='rbf', random_state=42)

# Melatih model menggunakan data pelatihan yang sudah diskalakan
svm_model_before_tuning.fit(X_train_scaled, y_train)

# Membuat prediksi pada data pengujian yang sudah diskalakan
y_pred_before_tuning = svm_model_before_tuning.predict(X_test_scaled)

# Mengevaluasi kinerja model
print("Model training complete (before tuning). Here are the evaluation metrics:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_before_tuning):.2f}") # Menampilkan akurasi
print("\nClassification Report:\n", classification_report(y_test, y_pred_before_tuning)) # Menampilkan classification report

from sklearn.model_selection import GridSearchCV # Mengimpor GridSearchCV untuk hyperparameter tuning
from sklearn.svm import SVC # Mengimpor Support Vector Classifier
from sklearn.metrics import accuracy_score, classification_report # Mengimpor metrik evaluasi model

# Mendefinisikan parameter grid untuk GridSearchCV
# C: Parameter regularisasi. Kekuatan regularisasi berbanding terbalik dengan C.
# gamma: Koefisien kernel untuk 'rbf', 'poly' dan 'sigmoid'.
param_grid = {
    'C': [0.1, 1, 10, 100], # Nilai-nilai C yang akan dicoba
    'gamma': [0.001, 0.01, 0.1, 1], # Nilai-nilai gamma yang akan dicoba
    'kernel': ['rbf'] # Menggunakan kernel rbf seperti yang telah ditentukan sebelumnya
}

# Menginisialisasi Support Vector Classifier dasar
svm_base_model = SVC(random_state=42)

# Menginisialisasi GridSearchCV
# cv=5 berarti 5-fold cross-validation
# verbose=3 akan menampilkan progres detail
# n_jobs=-1 akan menggunakan semua inti CPU yang tersedia
grid_search = GridSearchCV(svm_base_model, param_grid, cv=5, verbose=3, n_jobs=-1)

# Melatih GridSearchCV pada data pelatihan yang sudah diskalakan
print("Starting GridSearchCV for hyperparameter tuning...")
grid_search.fit(X_train_scaled, y_train)

# Menampilkan parameter terbaik dan skor terbaik yang ditemukan
print("\nGridSearchCV complete.")
print(f"Best parameters found: {grid_search.best_params_}") # Menampilkan parameter terbaik
print(f"Best cross-validation accuracy: {grid_search.best_score_:.2f}") # Menampilkan akurasi cross-validation terbaik

# Mendapatkan estimator (model) terbaik dari GridSearchCV
best_svm_model = grid_search.best_estimator_

# Membuat prediksi pada data pengujian yang sudah diskalakan menggunakan model terbaik
y_pred_tuned = best_svm_model.predict(X_test_scaled)

# Mengevaluasi model terbaik pada set pengujian
print("\nEvaluation of the best model on the test set:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_tuned):.2f}") # Menampilkan akurasi
print("\nClassification Report:\n", classification_report(y_test, y_pred_tuned)) # Menampilkan classification report

from sklearn.svm import SVC # Mengimpor Support Vector Classifier
from sklearn.metrics import accuracy_score, classification_report # Mengimpor metrik evaluasi model

# Parameter terbaik yang ditemukan dari GridSearchCV (dengan asumsi ini masih valid jika tidak dijalankan ulang)
best_params = {'C': 1, 'gamma': 0.01, 'kernel': 'rbf'}

# Menginisialisasi Support Vector Classifier dengan parameter terbaik
svm_model_after_tuning = SVC(**best_params, random_state=42)

# Melatih model menggunakan data pelatihan yang sudah diskalakan
svm_model_after_tuning.fit(X_train_scaled, y_train)

# Membuat prediksi pada data pengujian yang sudah diskalakan
y_pred_after_tuning = svm_model_after_tuning.predict(X_test_scaled)

# Mengevaluasi kinerja model
print("Model training complete (after tuning). Here are the evaluation metrics:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_after_tuning):.2f}") # Menampilkan akurasi
print("\nClassification Report:\n", classification_report(y_test, y_pred_after_tuning)) # Menampilkan classification report

from sklearn.svm import SVC # Mengimpor Support Vector Classifier
from sklearn.metrics import accuracy_score # Mengimpor fungsi accuracy_score
from sklearn.model_selection import train_test_split # Mengimpor fungsi untuk membagi data
from sklearn.preprocessing import StandardScaler # Mengimpor StandardScaler
import matplotlib.pyplot as plt # Mengimpor matplotlib untuk plotting
import seaborn as sns # Mengimpor seaborn untuk visualisasi
import pandas as pd # Mengimpor pandas untuk manipulasi DataFrame

# Menghitung akurasi baseline menggunakan y_test dan y_pred_after_tuning
baseline_accuracy = accuracy_score(y_test, y_pred_after_tuning)
print(f"Baseline Accuracy (All Features): {baseline_accuracy:.4f}") # Menampilkan akurasi baseline

# Menginisialisasi dictionary kosong untuk menyimpan hasil ablasi
ablation_results = {}

# Menambahkan akurasi baseline ke ablation_results
ablation_results['All Features'] = baseline_accuracy

# Mendefinisikan parameter terbaik yang ditemukan dari GridSearchCV (dengan asumsi ini masih valid jika tidak dijalankan ulang)
best_params = {'C': 1, 'gamma': 0.01, 'kernel': 'rbf'} # Parameter terbaik

# Mendapatkan nama fitur dari DataFrame X
feature_names = X.columns.tolist() # Daftar nama kolom fitur

print("\nStarting Feature Ablation Study...") # Pesan memulai studi ablasi

# 11. Menganalisis dan memvisualisasikan hasil studi ablasi fitur.
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Mengkonversi hasil ke DataFrame untuk analisis dan plotting yang lebih mudah.
ablation_df = pd.DataFrame(list(ablation_results.items()), columns=['Feature Removed', 'Accuracy'])

# Menghitung perubahan akurasi dibandingkan dengan baseline.
ablation_df['Accuracy Change'] = ablation_df['Accuracy'] - baseline_accuracy

# Mengurutkan berdasarkan dampak untuk visualisasi yang lebih baik.
ablation_df_sorted = ablation_df.sort_values(by='Accuracy Change', ascending=True)

print("\n--- Hasil Ablasi Fitur ---")
print(ablation_df_sorted)

# Memvisualisasikan hasilnya.
plt.figure(figsize=(12, 8))
sns.barplot(x='Accuracy Change', y='Feature Removed', hue='Feature Removed', data=ablation_df_sorted.iloc[1:], palette='viridis', legend=False) # Mengecualikan 'All Features' untuk plotting perubahan.

plt.axvline(x=0, color='r', linestyle='--', label='Tidak Berubah (Baseline)')
plt.title('Dampak Penghapusan Fitur Individual pada Akurasi Model SVM')
plt.xlabel('Perubahan Akurasi (vs. Baseline)')
plt.ylabel('Fitur yang Dihapus')
plt.legend()
plt.tight_layout()
plt.show()

print("Daftar fitur yang digunakan dalam model:")
display(X.columns.tolist())

print("\nPerforming Feature Ablation...") # Pesan memulai proses ablasi

for feature_to_remove in feature_names: # Iterasi melalui setiap nama fitur
    print(f"Processing: Removing feature '{feature_to_remove}'") # Pesan fitur yang sedang dihapus

    # 1. Membuat set fitur sementara dengan menjatuhkan satu fitur
    X_ablated = X.drop(columns=[feature_to_remove])

    # 2. Membagi ulang data menjadi set pelatihan dan pengujian
    X_train_ablated, X_test_ablated, y_train_ablated, y_test_ablated = train_test_split(
        X_ablated, y, test_size=0.2, random_state=42
    )

    # 3. Menskalakan ulang set fitur pelatihan dan pengujian yang baru
    scaler = StandardScaler() # Menginisialisasi StandardScaler
    X_train_ablated_scaled = scaler.fit_transform(X_train_ablated)
    X_test_ablated_scaled = scaler.transform(X_test_ablated)

    # 4. Melatih model SVM terbaik pada data pelatihan yang sudah diablasikan dan diskalakan
    svm_ablated_model = SVC(**best_params, random_state=42) # Menginisialisasi model SVM
    svm_ablated_model.fit(X_train_ablated_scaled, y_train_ablated) # Melatih model

    # 5. Membuat prediksi pada data pengujian yang sudah diablasikan dan diskalakan
    y_pred_ablated = svm_ablated_model.predict(X_test_ablated_scaled)

    # 6. Mengevaluasi akurasi model dan menyimpan hasilnya
    ablated_accuracy = accuracy_score(y_test_ablated, y_pred_ablated) # Menghitung akurasi
    ablation_results[feature_to_remove] = ablated_accuracy # Menyimpan hasil
    print(f"  Accuracy without '{feature_to_remove}': {ablated_accuracy:.4f}") # Menampilkan akurasi tanpa fitur tersebut

print("\nFeature Ablation Study Complete.") # Pesan studi ablasi selesai

import matplotlib.pyplot as plt # Mengimpor matplotlib untuk plotting
import seaborn as sns # Mengimpor seaborn untuk visualisasi
import pandas as pd # Mengimpor pandas untuk manipulasi DataFrame

# Mengkonversi hasil ke DataFrame untuk analisis dan plotting yang lebih mudah
ablation_df = pd.DataFrame(list(ablation_results.items()), columns=['Feature Removed', 'Accuracy']) # Membuat DataFrame dari hasil ablasi

# Menghitung perubahan akurasi dibandingkan dengan baseline
ablation_df['Accuracy Change'] = ablation_df['Accuracy'] - baseline_accuracy # Menghitung selisih akurasi

# Mengurutkan berdasarkan dampak untuk visualisasi yang lebih baik (fitur yang penghapusannya paling menurunkan akurasi ada di atas)
ablation_df_sorted = ablation_df.sort_values(by='Accuracy Change', ascending=True) # Mengurutkan DataFrame

# Menampilkan hasil ablasi
print("\n--- Ablation Results ---")
print(ablation_df_sorted) # Menampilkan DataFrame hasil ablasi yang sudah diurutkan

# Memvisualisasikan hasilnya
plt.figure(figsize=(12, 8)) # Mengatur ukuran figure
sns.barplot(x='Accuracy Change', y='Feature Removed', hue='Feature Removed', data=ablation_df_sorted.iloc[1:], palette='viridis', legend=False) # Membuat bar chart (mengecualikan 'All Features')

plt.axvline(x=0, color='r', linestyle='--', label='No Change (Baseline)') # Menambahkan garis vertikal pada x=0
plt.title('Impact of Individual Feature Removal on SVM Model Accuracy') # Judul plot
plt.xlabel('Change in Accuracy (vs. Baseline)') # Label sumbu X
plt.ylabel('Feature Removed') # Label sumbu Y
plt.legend() # Menampilkan legenda
plt.tight_layout() # Menyesuaikan layout
plt.show() # Menampilkan plot

# Meringkas temuan
print("\n--- Summary of Feature Ablation Study ---")
print(f"Baseline Accuracy (with all features): {baseline_accuracy:.4f}") # Menampilkan akurasi baseline

most_impactful_positive = ablation_df_sorted[ablation_df_sorted['Accuracy Change'] > 0].sort_values(by='Accuracy Change', ascending=False) # Fitur yang meningkatkan akurasi
most_impactful_negative = ablation_df_sorted[ablation_df_sorted['Accuracy Change'] < 0].sort_values(by='Accuracy Change', ascending=True) # Fitur yang menurunkan akurasi

if not most_impactful_positive.empty:
    print("\nFeatures whose removal *improved* accuracy (suggesting noise or redundancy):") # Judul
    for _, row in most_impactful_positive.iterrows():
        print(f"- '{row['Feature Removed']}': Accuracy increased by {row['Accuracy Change']:.4f}") # Menampilkan fitur yang meningkatkan akurasi
else:
    print("\nNo features improved accuracy when removed.") # Pesan jika tidak ada fitur yang meningkatkan akurasi

if not most_impactful_negative.empty:
    print("\nFeatures whose removal *decreased* accuracy (suggesting high importance):") # Judul
    for _, row in most_impactful_negative.iterrows():
        print(f"- '{row['Feature Removed']}': Accuracy decreased by {abs(row['Accuracy Change']):.4f}") # Menampilkan fitur yang menurunkan akurasi
else:
    print("\nNo features decreased accuracy when removed significantly.") # Pesan jika tidak ada fitur yang menurunkan akurasi secara signifikan

print("\nObservations:")
print("- A larger negative 'Accuracy Change' indicates a more important feature for the model's performance.") # Observasi
print("- A positive 'Accuracy Change' indicates that removing the feature actually improved performance, suggesting it might be noise or redundant.") # Observasi

import pandas as pd # Memastikan pandas diimpor untuk operasi DataFrame
from sklearn.metrics import confusion_matrix # Mengimpor fungsi confusion_matrix
import seaborn as sns # Mengimpor seaborn untuk visualisasi
import matplotlib.pyplot as plt # Mengimpor matplotlib untuk plotting
from sklearn.model_selection import train_test_split # Mengimpor fungsi untuk membagi data
from sklearn.preprocessing import StandardScaler # Mengimpor StandardScaler
from sklearn.svm import SVC # Mengimpor Support Vector Classifier

# Memuat file Excel ke dalam DataFrame pandas (jika belum dimuat)
df = pd.read_excel('/content/drive/MyDrive/Dataset/Dataset_Clean.xlsx')

# Mengatur opsi pandas untuk menampilkan semua kolom dan menghapus kolom kosong
pd.set_option('display.max_columns', None)
df = df.dropna(axis=1, how='all') # Menghapus kolom yang seluruhnya NaN

# Mendefinisikan ulang X dan y
# Mendefinisikan variabel target (y)
y = df['Label']
# Mendefinisikan fitur (X) dengan menjatuhkan kolom target dan kolom-kolom yang ditentukan
# 'Tempat saya berbelanja lebih banyak menyediakan QRIS' dihapus dari daftar drop sesuai tindakan manual pengguna
X = df.drop(columns=['Label', 'Saya lebih sering bertransaksi di toko modern'])

# --- Langkah Krusial: Tangani nilai NaN dengan menjatuhkan baris sebelum membagi dan menskalakan ---
# Menggabungkan X dan y untuk menjatuhkan baris dengan NaN secara konsisten di keduanya
df_combined = pd.concat([X, y], axis=1)
df_combined_cleaned = df_combined.dropna() # Menjatuhkan baris yang mengandung NaN

X = df_combined_cleaned.drop(columns=['Label']) # Memisahkan X dari DataFrame yang sudah bersih
y = df_combined_cleaned['Label'] # Memisahkan y dari DataFrame yang sudah bersih
# ----------------------------------------------------------------------

# Membagi ulang data ke dalam set pelatihan dan pengujian untuk memastikan y_test terdefinisi
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Menskalakan ulang data untuk memastikan X_test_scaled terdefinisi
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Melatih ulang model yang sudah disetel untuk memastikan y_pred_after_tuning terdefinisi
best_params = {'C': 1, 'gamma': 0.01, 'kernel': 'rbf'} # Parameter terbaik dari tuning
svm_model_after_tuning = SVC(**best_params, random_state=42) # Menginisialisasi model SVM dengan parameter terbaik
svm_model_after_tuning.fit(X_train_scaled, y_train) # Melatih model
y_pred_after_tuning = svm_model_after_tuning.predict(X_test_scaled) # Membuat prediksi

# Menghitung confusion matrix untuk model yang sudah disetel
cm = confusion_matrix(y_test, y_pred_after_tuning)

# Memplot confusion matrix
plt.figure(figsize=(8, 6)) # Mengatur ukuran figure
sns.heatmap(cm, annot=True, fmt='d', cmap='Greens',
            xticklabels=['Predicted 0', 'Predicted 1'], # Label sumbu X
            yticklabels=['Actual 0', 'Actual 1']) # Label sumbu Y
plt.xlabel('Predicted Label') # Label sumbu X
plt.ylabel('True Label') # Label sumbu Y
plt.title('Confusion Matrix for Tuned SVM Model') # Judul plot
plt.show() # Menampilkan plot

import pandas as pd # Mengimpor library pandas

# Memuat file Excel ke dalam DataFrame pandas (memastikan df tersedia)
df = pd.read_excel('/content/drive/MyDrive/Dataset/Dataset_Clean.xlsx')

# Menghapus kolom-kolom yang seluruhnya kosong (berisi semua nilai NaN)
df = df.dropna(axis=1, how='all')

# Mendefinisikan variabel target (y) dan fitur (X) untuk memastikan keduanya tersedia
y = df['Label'] # Variabel target
# Mendefinisikan fitur (X) dengan menjatuhkan kolom target dan kolom-kolom yang ditentukan
# 'Tempat saya berbelanja lebih banyak menyediakan QRIS' dihapus dari daftar drop sesuai tindakan manual pengguna
X = df.drop(columns=['Label', 'Saya lebih sering bertransaksi di toko modern']) # Fitur

# Memeriksa distribusi variabel target (y)
print("Distribution of target variable (y):")
display(y.value_counts()) # Menampilkan jumlah nilai unik dari y

# Menghitung distribusi persentase
print("\nPercentage distribution of target variable (y):")
display(y.value_counts(normalize=True) * 100) # Menampilkan persentase nilai unik dari y

import pandas as pd # Memastikan pandas diimpor untuk operasi DataFrame
from sklearn.metrics import confusion_matrix # Mengimpor fungsi confusion_matrix
import seaborn as sns # Mengimpor seaborn untuk visualisasi
import matplotlib.pyplot as plt # Mengimpor matplotlib untuk plotting
from sklearn.model_selection import train_test_split # Mengimpor fungsi untuk membagi data
from sklearn.preprocessing import StandardScaler # Mengimpor StandardScaler
from sklearn.svm import SVC # Mengimpor Support Vector Classifier

# Memuat file Excel ke dalam DataFrame pandas (jika belum dimuat)
df = pd.read_excel('/content/drive/MyDrive/Dataset/Dataset_Clean.xlsx')

# Mengatur opsi pandas untuk menampilkan semua kolom dan menghapus kolom kosong
pd.set_option('display.max_columns', None)
df = df.dropna(axis=1, how='all') # Menghapus kolom yang seluruhnya NaN

# Mendefinisikan ulang X dan y
# Mendefinisikan variabel target (y)
y = df['Label']
# Mendefinisikan fitur (X) dengan menjatuhkan kolom target dan kolom-kolom yang ditentukan
# 'Tempat saya berbelanja lebih banyak menyediakan QRIS' dihapus dari daftar drop sesuai tindakan manual pengguna
X = df.drop(columns=['Label', 'Saya lebih sering bertransaksi di toko modern'])

# --- Langkah Krusial: Tangani nilai NaN dengan menjatuhkan baris sebelum membagi dan menskalakan ---
# Menggabungkan X dan y untuk menjatuhkan baris dengan NaN secara konsisten di keduanya
df_combined = pd.concat([X, y], axis=1)
df_combined_cleaned = df_combined.dropna() # Menjatuhkan baris yang mengandung NaN

X = df_combined_cleaned.drop(columns=['Label']) # Memisahkan X dari DataFrame yang sudah bersih
y = df_combined_cleaned['Label'] # Memisahkan y dari DataFrame yang sudah bersih
# ----------------------------------------------------------------------

# Membagi ulang data ke dalam set pelatihan dan pengujian untuk memastikan y_test terdefinisi
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Menskalakan ulang data untuk memastikan X_test_scaled terdefinisi
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Melatih ulang model yang sudah disetel untuk memastikan y_pred_after_tuning terdefinisi
best_params = {'C': 1, 'gamma': 0.01, 'kernel': 'rbf'} # Parameter terbaik dari tuning
svm_model_after_tuning = SVC(**best_params, random_state=42) # Menginisialisasi model SVM dengan parameter terbaik
svm_model_after_tuning.fit(X_train_scaled, y_train) # Melatih model
y_pred_after_tuning = svm_model_after_tuning.predict(X_test_scaled) # Membuat prediksi

# Menghitung confusion matrix untuk model yang sudah disetel
cm = confusion_matrix(y_test, y_pred_after_tuning)

# Memplot confusion matrix
plt.figure(figsize=(8, 6)) # Mengatur ukuran figure
sns.heatmap(cm, annot=True, fmt='d', cmap='Greens',
            xticklabels=['Predicted 0', 'Predicted 1'], # Label sumbu X
            yticklabels=['Actual 0', 'Actual 1']) # Label sumbu Y
plt.xlabel('Predicted Label') # Label sumbu X
plt.ylabel('True Label') # Label sumbu Y
plt.title('Confusion Matrix for Tuned SVM Model') # Judul plot
plt.show() # Menampilkan plot

import pandas as pd # Mengimpor library pandas

# Memuat file Excel ke dalam DataFrame pandas (memastikan df tersedia)
df = pd.read_excel('/content/drive/MyDrive/Dataset/Dataset_Clean.xlsx')

# Menghapus kolom-kolom yang seluruhnya kosong (berisi semua nilai NaN)
df = df.dropna(axis=1, how='all')

# Mendefinisikan variabel target (y) dan fitur (X) untuk memastikan keduanya tersedia
y = df['Label'] # Variabel target
# Mendefinisikan fitur (X) dengan menjatuhkan kolom target dan kolom-kolom yang ditentukan
# 'Tempat saya berbelanja lebih banyak menyediakan QRIS' dihapus dari daftar drop sesuai tindakan manual pengguna
X = df.drop(columns=['Label', 'Saya lebih sering bertransaksi di toko modern']) # Fitur

# Memeriksa distribusi variabel target (y)
print("Distribution of target variable (y):")
display(y.value_counts()) # Menampilkan jumlah nilai unik dari y

# Menghitung distribusi persentase
print("\nPercentage distribution of target variable (y):")
display(y.value_counts(normalize=True) * 100) # Menampilkan persentase nilai unik dari y

"""### Model Training (After Hyperparameter Tuning with Best Parameters)"""

from sklearn.svm import SVC # Mengimpor Support Vector Classifier
from sklearn.metrics import accuracy_score, classification_report # Mengimpor metrik evaluasi model

# Parameter terbaik yang ditemukan dari GridSearchCV (dengan asumsi ini masih valid jika tidak dijalankan ulang)
best_params = {'C': 1, 'gamma': 0.01, 'kernel': 'rbf'}

# Menginisialisasi Support Vector Classifier dengan parameter terbaik
svm_model_after_tuning = SVC(**best_params, random_state=42)

# Melatih model menggunakan data pelatihan yang sudah diskalakan
svm_model_after_tuning.fit(X_train_scaled, y_train)

# Membuat prediksi pada data pengujian yang sudah diskalakan
y_pred_after_tuning = svm_model_after_tuning.predict(X_test_scaled)

# Mengevaluasi kinerja model
print("Model training complete (after tuning). Here are the evaluation metrics:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_after_tuning):.2f}") # Menampilkan akurasi
print("\nClassification Report:\n", classification_report(y_test, y_pred_after_tuning)) # Menampilkan classification report

from sklearn.model_selection import GridSearchCV # Mengimpor GridSearchCV untuk hyperparameter tuning
from sklearn.svm import SVC # Mengimpor Support Vector Classifier
from sklearn.metrics import accuracy_score, classification_report # Mengimpor metrik evaluasi model

# Mendefinisikan parameter grid untuk GridSearchCV
# C: Parameter regularisasi. Kekuatan regularisasi berbanding terbalik dengan C.
# gamma: Koefisien kernel untuk 'rbf', 'poly' dan 'sigmoid'.
param_grid = {
    'C': [0.1, 1, 10, 100], # Nilai-nilai C yang akan dicoba
    'gamma': [0.001, 0.01, 0.1, 1], # Nilai-nilai gamma yang akan dicoba
    'kernel': ['rbf'] # Menggunakan kernel rbf seperti yang telah ditentukan sebelumnya
}

# Menginisialisasi Support Vector Classifier dasar
svm_base_model = SVC(random_state=42)

# Menginisialisasi GridSearchCV
# cv=5 berarti 5-fold cross-validation
# verbose=3 akan menampilkan progres detail
# n_jobs=-1 akan menggunakan semua inti CPU yang tersedia
grid_search = GridSearchCV(svm_base_model, param_grid, cv=5, verbose=3, n_jobs=-1)

# Melatih GridSearchCV pada data pelatihan yang sudah diskalakan
print("Starting GridSearchCV for hyperparameter tuning...")
grid_search.fit(X_train_scaled, y_train)

# Menampilkan parameter terbaik dan skor terbaik yang ditemukan
print("\nGridSearchCV complete.")
print(f"Best parameters found: {grid_search.best_params_}") # Menampilkan parameter terbaik
print(f"Best cross-validation accuracy: {grid_search.best_score_:.2f}") # Menampilkan akurasi cross-validation terbaik

# Mendapatkan estimator (model) terbaik dari GridSearchCV
best_svm_model = grid_search.best_estimator_

# Membuat prediksi pada data pengujian yang sudah diskalakan menggunakan model terbaik
y_pred_tuned = best_svm_model.predict(X_test_scaled)

# Mengevaluasi model terbaik pada set pengujian
print("\nEvaluation of the best model on the test set:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_tuned):.2f}") # Menampilkan akurasi
print("\nClassification Report:\n", classification_report(y_test, y_pred_tuned)) # Menampilkan classification report

# Mendefinisikan variabel target (y)
y = df['Label']

# Mendefinisikan fitur (X) dengan menjatuhkan kolom target dan kolom-kolom yang ditentukan dari DataFrame
# 'Tempat saya berbelanja lebih banyak menyediakan QRIS' dihapus dari daftar drop sesuai tindakan manual pengguna
X = df.drop(columns=['Label', 'Unnamed: 27', 'Saya lebih sering bertransaksi di toko modern']) # Kolom yang dijatuhkan

# Menampilkan beberapa baris pertama dari X dan y untuk konfirmasi
print("Features (X) head:")
display(X.head()) # Menampilkan head dari DataFrame fitur
print("\nTarget (y) head:")
display(y.head()) # Menampilkan head dari Series target

"""For SVM (Support Vector Machine) in Python, the most commonly used libraries are:

*   **`scikit-learn`**: This is the most popular library for machine learning in Python and provides various SVM implementations (`SVC`, `SVR`, `LinearSVC`, `NuSVC`, `NuSVR`).
*   **`numpy`**: Often used for numerical operations and array manipulation.
*   **`pandas`**: Used for data manipulation and analysis, especially for handling DataFrames.
*   **`matplotlib`** and **`seaborn`**: For data visualization to understand the data and SVM model performance.

# Task
The user wants to perform a feature ablation study on the SVM model. This involves iteratively removing each feature, retraining the model, and evaluating its performance to determine the impact of each feature. The results will then be visualized and summarized.

Specifically, the task is to:
1.  **Prepare for Ablation**: Initialize a dictionary to store the accuracy when each feature is removed.
2.  **Perform Feature Ablation**:
    *   Iterate through each feature in the `X` DataFrame.
    *   For each feature, create a temporary dataset by dropping that feature.
    *   Re-split the data into training and testing sets.
    *   Re-scale the training and testing sets.
    *   Train a new SVM model using the best hyperparameters found previously (`C=1`, `gamma=0.01`, `kernel='rbf'`) on this ablated data.
    *   Evaluate the model's accuracy on the ablated test set.
    *   Store the accuracy with the name of the removed feature.
3.  **Analyze and Visualize Ablation Results**:
    *   Compare the accuracy obtained when each feature was removed against the baseline accuracy (accuracy of the model with all features, which is 0.74).
    *   Create a bar chart showing the change in accuracy for each removed feature.
4.  **Summarize Findings**: Conclude which features had the most significant impact on the model's performance.

Let's begin by defining the baseline accuracy and initializing the storage for ablation results.

```python
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Baseline accuracy (from the best model trained with all features)
# This was calculated in cell dd8401ab or 5308e91a
baseline_accuracy = accuracy_score(y_test, y_pred_after_tuning)
print(f"Baseline Accuracy (with all features): {baseline_accuracy:.4f}")

# Store ablation results
ablation_results = {}
ablation_results['All Features'] = baseline_accuracy

# Best parameters found from GridSearchCV
best_params = {'C': 1, 'gamma': 0.01, 'kernel': 'rbf'}

# Get the list of feature names
feature_names = X.columns

print("\nStarting Feature Ablation Study...")

for feature_to_remove in feature_names:
    print(f"Processing: Removing feature '{feature_to_remove}'")

    # 1. Create a temporary feature set by dropping one feature
    X_ablated = X.drop(columns=[feature_to_remove])

    # 2. Re-split the data into training and testing sets
    X_train_ablated, X_test_ablated, y_train_ablated, y_test_ablated = train_test_split(
        X_ablated, y, test_size=0.2, random_state=42
    )

    # 3. Re-scale the new training and testing feature sets
    scaler = StandardScaler()
    X_train_ablated_scaled = scaler.fit_transform(X_train_ablated)
    X_test_ablated_scaled = scaler.transform(X_test_ablated)

    # 4. Train the best SVM model on the ablated and scaled training data
    svm_ablated_model = SVC(**best_params, random_state=42)
    svm_ablated_model.fit(X_train_ablated_scaled, y_train_ablated)

    # 5. Make predictions on the ablated and scaled test data
    y_pred_ablated = svm_ablated_model.predict(X_test_ablated_scaled)

    # 6. Evaluate the model's accuracy and store the result
    ablated_accuracy = accuracy_score(y_test_ablated, y_pred_ablated)
    ablation_results[feature_to_remove] = ablated_accuracy
    print(f"  Accuracy without '{feature_to_remove}': {ablated_accuracy:.4f}")

print("\nFeature Ablation Study Complete.")

# Convert results to a DataFrame for easier analysis and plotting
ablation_df = pd.DataFrame(list(ablation_results.items()), columns=['Feature Removed', 'Accuracy'])

# Calculate the change in accuracy compared to the baseline
ablation_df['Accuracy Change'] = ablation_df['Accuracy'] - baseline_accuracy

# Sort by impact for better visualization (features whose removal drops accuracy most are at the top)
ablation_df_sorted = ablation_df.sort_values(by='Accuracy Change', ascending=True)

# Display the ablation results
print("\n--- Ablation Results ---")
print(ablation_df_sorted)

# Visualize the results
plt.figure(figsize=(12, 8))
sns.barplot(x='Accuracy Change', y='Feature Removed', data=ablation_df_sorted.iloc[1:], palette='viridis') # Exclude 'All Features' for plotting change

plt.axvline(x=0, color='r', linestyle='--', label='No Change (Baseline)')
plt.title('Impact of Individual Feature Removal on SVM Model Accuracy')
plt.xlabel('Change in Accuracy (vs. Baseline)')
plt.ylabel('Feature Removed')
plt.legend()
plt.tight_layout()
plt.show()

# Summarize findings
print("\n--- Summary of Feature Ablation Study ---")
print(f"Baseline Accuracy (with all features): {baseline_accuracy:.4f}")

most_impactful_positive = ablation_df_sorted[ablation_df_sorted['Accuracy Change'] > 0].sort_values(by='Accuracy Change', ascending=False)
most_impactful_negative = ablation_df_sorted[ablation_df_sorted['Accuracy Change'] < 0].sort_values(by='Accuracy Change', ascending=True)

if not most_impactful_positive.empty:
    print("\nFeatures whose removal *improved* accuracy (suggesting noise or redundancy):")
    for _, row in most_impactful_positive.iterrows():
        print(f"- '{row['Feature Removed']}': Accuracy increased by {row['Accuracy Change']:.4f}")
else:
    print("\nNo features improved accuracy when removed.")

if not most_impactful_negative.empty:
    print("\nFeatures whose removal *decreased* accuracy (suggesting high importance):")
    for _, row in most_impactful_negative.iterrows():
        print(f"- '{row['Feature Removed']}': Accuracy decreased by {abs(row['Accuracy Change']):.4f}")
else:
    print("\nNo features decreased accuracy when removed significantly.")

print("\nObservations:")
print("- A larger negative 'Accuracy Change' indicates a more important feature for the model's performance.")
print("- A positive 'Accuracy Change' indicates that removing the feature actually improved performance, suggesting it might be noise or redundant.")
```

## Prepare for Ablation

### Subtask:
Initialize an empty dictionary to store the model performance (e.g., accuracy) for each ablation step. This will help compare the results against the baseline model (with all features).

**Reasoning**:
The subtask requires initializing an empty dictionary for ablation results, calculating baseline accuracy, and setting up parameters and feature names for the ablation study. These steps can be combined into a single code block for efficiency.
"""

from sklearn.svm import SVC # Mengimpor Support Vector Classifier
from sklearn.metrics import accuracy_score # Mengimpor fungsi accuracy_score
from sklearn.model_selection import train_test_split # Mengimpor fungsi untuk membagi data
from sklearn.preprocessing import StandardScaler # Mengimpor StandardScaler
import matplotlib.pyplot as plt # Mengimpor matplotlib untuk plotting
import seaborn as sns # Mengimpor seaborn untuk visualisasi
import pandas as pd # Mengimpor pandas untuk manipulasi DataFrame

# Menghitung akurasi baseline menggunakan y_test dan y_pred_after_tuning
baseline_accuracy = accuracy_score(y_test, y_pred_after_tuning)
print(f"Baseline Accuracy (All Features): {baseline_accuracy:.4f}") # Menampilkan akurasi baseline

# Menginisialisasi dictionary kosong untuk menyimpan hasil ablasi
ablation_results = {}

# Menambahkan akurasi baseline ke ablation_results
ablation_results['All Features'] = baseline_accuracy

# Mendefinisikan parameter terbaik yang ditemukan dari GridSearchCV (dengan asumsi ini masih valid jika tidak dijalankan ulang)
best_params = {'C': 1, 'gamma': 0.01, 'kernel': 'rbf'} # Parameter terbaik

# Mendapatkan nama fitur dari DataFrame X
feature_names = X.columns.tolist() # Daftar nama kolom fitur

print("\nStarting Feature Ablation Study...") # Pesan memulai studi ablasi

# --- Langkah Krusial: Tangani nilai NaN dengan menjatuhkan baris dari X dan y ---
# Menggabungkan X dan y untuk menjatuhkan baris dengan NaN secara konsisten di keduanya
df_combined = pd.concat([X, y], axis=1)

# Menjatuhkan baris yang mengandung nilai NaN apa pun
df_combined_cleaned = df_combined.dropna()

# Memisahkan X dan y lagi dari DataFrame gabungan yang sudah dibersihkan
X = df_combined_cleaned.drop(columns=['Label']) # Fitur X yang sudah bersih
y = df_combined_cleaned['Label'] # Variabel target y yang sudah bersih

print(f"Shape of X after dropping rows with NaNs: {X.shape}") # Menampilkan bentuk X setelah drop NaNs
print(f"Shape of y after dropping rows with NaNs: {y.shape}") # Menampilkan bentuk y setelah drop NaNs
print("Number of NaN values per column in X after cleaning:") # Menampilkan jumlah NaN per kolom di X (seharusnya 0)
display(X.isnull().sum()[X.isnull().sum() > 0])
print("Number of NaN values per column in y after cleaning:") # Menampilkan jumlah NaN per kolom di y (seharusnya 0)
display(y.isnull().sum()[y.isnull().sum() > 0])

"""**Reasoning**:
The previous step successfully initialized the `ablation_results` dictionary, calculated baseline accuracy, and set up the necessary parameters. The next logical step is to iterate through each feature, drop it, retrain the model with the best parameters, evaluate its performance, and store the results in the `ablation_results` dictionary as per the subtask's instructions to 'Perform Feature Ablation'.


"""

print("\nPerforming Feature Ablation...") # Pesan memulai proses ablasi

for feature_to_remove in feature_names: # Iterasi melalui setiap nama fitur
    print(f"Processing: Removing feature '{feature_to_remove}'") # Pesan fitur yang sedang dihapus

    # 1. Membuat set fitur sementara dengan menjatuhkan satu fitur
    X_ablated = X.drop(columns=[feature_to_remove])

    # 2. Membagi ulang data menjadi set pelatihan dan pengujian
    X_train_ablated, X_test_ablated, y_train_ablated, y_test_ablated = train_test_split(
        X_ablated, y, test_size=0.2, random_state=42
    )

    # 3. Menskalakan ulang set fitur pelatihan dan pengujian yang baru
    scaler = StandardScaler() # Menginisialisasi StandardScaler
    X_train_ablated_scaled = scaler.fit_transform(X_train_ablated)
    X_test_ablated_scaled = scaler.transform(X_test_ablated)

    # 4. Melatih model SVM terbaik pada data pelatihan yang sudah diablasikan dan diskalakan
    svm_ablated_model = SVC(**best_params, random_state=42) # Menginisialisasi model SVM
    svm_ablated_model.fit(X_train_ablated_scaled, y_train_ablated) # Melatih model

    # 5. Membuat prediksi pada data pengujian yang sudah diablasikan dan diskalakan
    y_pred_ablated = svm_ablated_model.predict(X_test_ablated_scaled)

    # 6. Mengevaluasi akurasi model dan menyimpan hasilnya
    ablated_accuracy = accuracy_score(y_test_ablated, y_pred_ablated) # Menghitung akurasi
    ablation_results[feature_to_remove] = ablated_accuracy # Menyimpan hasil
    print(f"  Accuracy without '{feature_to_remove}': {ablated_accuracy:.4f}") # Menampilkan akurasi tanpa fitur tersebut

print("\nFeature Ablation Study Complete.") # Pesan studi ablasi selesai

"""**Reasoning**:
The feature ablation study has been completed, and results are stored in `ablation_results`. The next step is to analyze and visualize these results by converting them into a DataFrame, calculating accuracy changes from the baseline, sorting, and then creating a bar chart to visualize the impact of each feature, followed by a summary of findings.


"""

import matplotlib.pyplot as plt # Mengimpor matplotlib untuk plotting
import seaborn as sns # Mengimpor seaborn untuk visualisasi
import pandas as pd # Mengimpor pandas untuk manipulasi DataFrame

# Mengkonversi hasil ke DataFrame untuk analisis dan plotting yang lebih mudah
ablation_df = pd.DataFrame(list(ablation_results.items()), columns=['Feature Removed', 'Accuracy']) # Membuat DataFrame dari hasil ablasi

# Menghitung perubahan akurasi dibandingkan dengan baseline
ablation_df['Accuracy Change'] = ablation_df['Accuracy'] - baseline_accuracy # Menghitung selisih akurasi

# Mengurutkan berdasarkan dampak untuk visualisasi yang lebih baik (fitur yang penghapusannya paling menurunkan akurasi ada di atas)
ablation_df_sorted = ablation_df.sort_values(by='Accuracy Change', ascending=True) # Mengurutkan DataFrame

# Menampilkan hasil ablasi
print("\n--- Ablation Results ---")
print(ablation_df_sorted) # Menampilkan DataFrame hasil ablasi yang sudah diurutkan

# Memvisualisasikan hasilnya
plt.figure(figsize=(12, 8)) # Mengatur ukuran figure
sns.barplot(x='Accuracy Change', y='Feature Removed', data=ablation_df_sorted.iloc[1:], palette='viridis') # Membuat bar chart (mengecualikan 'All Features')

plt.axvline(x=0, color='r', linestyle='--', label='No Change (Baseline)') # Menambahkan garis vertikal pada x=0
plt.title('Impact of Individual Feature Removal on SVM Model Accuracy') # Judul plot
plt.xlabel('Change in Accuracy (vs. Baseline)') # Label sumbu X
plt.ylabel('Feature Removed') # Label sumbu Y
plt.legend() # Menampilkan legenda
plt.tight_layout() # Menyesuaikan layout
plt.show() # Menampilkan plot

# Meringkas temuan
print("\n--- Summary of Feature Ablation Study ---")
print(f"Baseline Accuracy (with all features): {baseline_accuracy:.4f}") # Menampilkan akurasi baseline

most_impactful_positive = ablation_df_sorted[ablation_df_sorted['Accuracy Change'] > 0].sort_values(by='Accuracy Change', ascending=False) # Fitur yang meningkatkan akurasi
most_impactful_negative = ablation_df_sorted[ablation_df_sorted['Accuracy Change'] < 0].sort_values(by='Accuracy Change', ascending=True) # Fitur yang menurunkan akurasi

if not most_impactful_positive.empty:
    print("\nFeatures whose removal *improved* accuracy (suggesting noise or redundancy):") # Judul
    for _, row in most_impactful_positive.iterrows():
        print(f"- '{row['Feature Removed']}': Accuracy increased by {row['Accuracy Change']:.4f}") # Menampilkan fitur yang meningkatkan akurasi
else:
    print("\nNo features improved accuracy when removed.") # Pesan jika tidak ada fitur yang meningkatkan akurasi

if not most_impactful_negative.empty:
    print("\nFeatures whose removal *decreased* accuracy (suggesting high importance):") # Judul
    for _, row in most_impactful_negative.iterrows():
        print(f"- '{row['Feature Removed']}': Accuracy decreased by {abs(row['Accuracy Change']):.4f}") # Menampilkan fitur yang menurunkan akurasi
else:
    print("\nNo features decreased accuracy when removed significantly.") # Pesan jika tidak ada fitur yang menurunkan akurasi secara signifikan

print("\nObservations:")
print("- A larger negative 'Accuracy Change' indicates a more important feature for the model's performance.") # Observasi
print("- A positive 'Accuracy Change' indicates that removing the feature actually improved performance, suggesting it might be noise or redundant.") # Observasi

"""**Reasoning**:
The previous code generated a `FutureWarning` because `palette` was used without assigning a `hue` variable in `sns.barplot`. To fix this and follow best practices, I will assign the `y` variable to `hue` and set `legend=False` in the `barplot` function.


"""

import matplotlib.pyplot as plt # Mengimpor matplotlib untuk plotting
import seaborn as sns # Mengimpor seaborn untuk visualisasi
import pandas as pd # Mengimpor pandas untuk manipulasi DataFrame

# Mengkonversi hasil ke DataFrame untuk analisis dan plotting yang lebih mudah
ablation_df = pd.DataFrame(list(ablation_results.items()), columns=['Feature Removed', 'Accuracy']) # Membuat DataFrame dari hasil ablasi

# Menghitung perubahan akurasi dibandingkan dengan baseline
ablation_df['Accuracy Change'] = ablation_df['Accuracy'] - baseline_accuracy # Menghitung selisih akurasi

# Mengurutkan berdasarkan dampak untuk visualisasi yang lebih baik (fitur yang penghapusannya paling menurunkan akurasi ada di atas)
ablation_df_sorted = ablation_df.sort_values(by='Accuracy Change', ascending=True) # Mengurutkan DataFrame

# Menampilkan hasil ablasi
print("\n--- Ablation Results ---")
print(ablation_df_sorted) # Menampilkan DataFrame hasil ablasi yang sudah diurutkan

# Memvisualisasikan hasilnya
plt.figure(figsize=(12, 8)) # Mengatur ukuran figure
sns.barplot(x='Accuracy Change', y='Feature Removed', hue='Feature Removed', data=ablation_df_sorted.iloc[1:], palette='viridis', legend=False) # Membuat bar chart (mengecualikan 'All Features')

plt.axvline(x=0, color='r', linestyle='--', label='No Change (Baseline)') # Menambahkan garis vertikal pada x=0
plt.title('Impact of Individual Feature Removal on SVM Model Accuracy') # Judul plot
plt.xlabel('Change in Accuracy (vs. Baseline)') # Label sumbu X
plt.ylabel('Feature Removed') # Label sumbu Y
plt.legend() # Menampilkan legenda
plt.tight_layout() # Menyesuaikan layout
plt.show() # Menampilkan plot

# Meringkas temuan
print("\n--- Summary of Feature Ablation Study ---")
print(f"Baseline Accuracy (with all features): {baseline_accuracy:.4f}") # Menampilkan akurasi baseline

most_impactful_positive = ablation_df_sorted[ablation_df_sorted['Accuracy Change'] > 0].sort_values(by='Accuracy Change', ascending=False) # Fitur yang meningkatkan akurasi
most_impactful_negative = ablation_df_sorted[ablation_df_sorted['Accuracy Change'] < 0].sort_values(by='Accuracy Change', ascending=True) # Fitur yang menurunkan akurasi

if not most_impactful_positive.empty:
    print("\nFeatures whose removal *improved* accuracy (suggesting noise or redundancy):") # Judul
    for _, row in most_impactful_positive.iterrows():
        print(f"- '{row['Feature Removed']}': Accuracy increased by {row['Accuracy Change']:.4f}") # Menampilkan fitur yang meningkatkan akurasi
else:
    print("\nNo features improved accuracy when removed.") # Pesan jika tidak ada fitur yang meningkatkan akurasi

if not most_impactful_negative.empty:
    print("\nFeatures whose removal *decreased* accuracy (suggesting high importance):") # Judul
    for _, row in most_impactful_negative.iterrows():
        print(f"- '{row['Feature Removed']}': Accuracy decreased by {abs(row['Accuracy Change']):.4f}") # Menampilkan fitur yang menurunkan akurasi
else:
    print("\nNo features decreased accuracy when removed significantly.") # Pesan jika tidak ada fitur yang menurunkan akurasi secara signifikan

print("\nObservations:")
print("- A larger negative 'Accuracy Change' indicates a more important feature for the model's performance.") # Observasi
print("- A positive 'Accuracy Change' indicates that removing the feature actually improved performance, suggesting it might be noise or redundant.") # Observasi

"""## Summary:

### Data Analysis Key Findings
*   **Baseline Performance**: The SVM model, when trained with all features, achieved a baseline accuracy of 0.7417.
*   **Most Impactful Features (Decreased Accuracy upon Removal)**:
    *   Removing the feature '7. Seberapa sering Anda menggunakan aplikasi keuangan (e-wallet/mobile banking)?' led to the largest decrease in accuracy, dropping by 0.0250 to 0.7167. This indicates it is the most crucial feature for the model's performance.
    *   Features '5. Perangkat smartphone yang saya gunakan selalu siap dan mampu untuk melakukan scan 1 dengan baik ' and 'Saya pernah mengalami QRIS lambat saat dipindai.' also contributed significantly, with their removal each decreasing accuracy by 0.0083.
*   **Features Suggesting Redundancy or Noise (Increased Accuracy upon Removal)**:
    *   Removing the feature 'Membawa uang tunai dalam jumlah banyak terasa tidak aman bagi saya' resulted in an accuracy improvement of 0.0250, increasing to 0.7667. This suggests the feature might be noisy or redundant.
    *   Other features, including '4. Pendapatan per bulan?', '10. QRIS lebih cepat dibanding pembayaran Tunai ', '11. QRIS aman digunakan ', '14. Berapa rata-rata nominal transaksi Anda per pembelian?', and 'Saya merasa uang lebih cepat habis jika membayar tunai.', also led to a slight accuracy increase of 0.0083 each when removed.

### Insights or Next Steps
*   Consider removing features that, when ablated, lead to an increase in model accuracy (e.g., 'Membawa uang tunai dalam jumlah banyak terasa tidak aman bagi saya') as they might be introducing noise or redundancy, potentially simplifying the model and improving its generalization.
*   The features '7. Seberapa sering Anda menggunakan aplikasi keuangan (e-wallet/mobile banking)?', '5. Perangkat smartphone yang saya gunakan selalu siap dan mampu untuk melakukan scan 1 dengan baik ', and 'Saya pernah mengalami QRIS lambat saat dipindai.' are critical for the model's predictive power. Further investigation into these features, such as exploring their interaction with other variables, could provide deeper insights into the underlying patterns.

"""